version: "3"
services:
  db:
    env_file: ./.envs/.local/.postgres

  api:
    build:
      context: ./api/
      args:
        INSTALL_DEV_DEPENDENCIES: "true"
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it db:5432 -- poetry run ./manage.py migrate && poetry run ./manage.py runserver 0.0.0.0:8000",
      ]
    env_file: ./.envs/.local/.api

  caluma:
    build:
      context: caluma
      args:
        INSTALL_DEV: "true"
    env_file: ./.envs/.local/.caluma
    volumes:
      - ./caluma/extensions:/app/caluma/extensions
      - ./caluma/data:/app/caluma/data:ro
      - ./caluma/setup.cfg:/app/setup.cfg:ro
      - ./caluma/.env:/app/.env
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it db:5432 -- poetry run python ./manage.py migrate && poetry run python ./manage.py runserver 0.0.0.0:8000",
      ]

  caddy:
    env_file: ./.envs/.local/.caddy
    environment:
      - GRAPHIQL_PROXY=reverse_proxy /static/graphene_django/* http://caluma:8000
    networks:
      default:
        aliases:
          - mysagw.local

  keycloak:
    env_file: ./.envs/.local/.keycloak

  mail:
    image: mailhog/mailhog
    environment:
      - VIRTUAL_PORT=8025
      - VIRTUAL_HOST=mail.mysagw.local
    ports:
      - "8025:8025"

  minio:
    env_file: ./.envs/.local/.minio
    ports:
      - "9000:9000"

  mc:
    env_file: ./.envs/.local/.minio

  dms:
    env_file: ./.envs/.local/.dms
