version: 1
update_configs:
  - package_manager: "python"
    directory: "/api"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
    ignored_updates:
      - match:
          dependency_name: "django"
          version_requirement: ">=3"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "docker"
    directory: "/api"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
    ignored_updates:
      - match:
          dependency_name: "python"
          version_requirement: ">=3.9"
  - package_manager: "javascript"
    directory: "/ember"
    update_schedule: "daily"
    version_requirement_updates: "increase_versions"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
